# Generated by Django 2.2.12 on 2020-04-07 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VisualizingTweets', '0002_auto_20200407_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='user_name',
            new_name='screen_name',
        ),
    ]
