# Generated by Django 2.2.12 on 2020-04-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VisualizingTweets', '0003_auto_20200407_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='ユーザー名'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='screen_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='screen_name'),
        ),
    ]
