# Generated by Django 2.2.12 on 2020-04-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VisualizingTweets', '0004_auto_20200407_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
    ]
