# Generated by Django 2.2.12 on 2020-04-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VisualizingTweets', '0005_auto_20200408_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ストック日'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='screen_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='ハンドルネーム'),
        ),
    ]
