# Generated by Django 2.2.12 on 2020-05-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VisualizingTweets', '0006_auto_20200408_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='ストック日'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='screen_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ハンドルネーム'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='tweet_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ツイート日'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='tweet_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ツイートID'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='tweet_text',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='ツイート内容'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='tweet_url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='ツイートURL'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新日'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='user_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ユーザー名'),
        ),
    ]
