name: docker-compose build,test,deploy to Heroku

on: [push]

jobs:

  build:
    name: build,test
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: config.ci_settings
      CONSUMER_KEY : ${{ secrets.CONSUMER_KEY }}
      CONSUMER_SECRET : ${{ secrets.CONSUMER_SECRET }}
      ACCESS_TOKEN : ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET : ${{ secrets.ACCESS_TOKEN_SECRET }}
      YOUTUBE_API_KEY : ${{ secrets.YOUTUBE_API_KEY }}

    steps:
    - uses: actions/checkout@v1
    - name: Build the docker-compose stack
      run: docker-compose -f docker-compose.ci.yml up -d
    - name: Check running containers
      run: docker ps -a
    - name: Check logs
      run: docker logs visualizingTweets-django

    # - name: Run test suite
      # run: docker exec visualizingTweets-django python manage.py test

  deploy:
    name: deploy to Heroku
    runs-on: ubuntu-latest

    needs: [build]
    steps:
    - uses: actions/checkout@v1
    - name: Push to Heroku
      run: git push -f https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP }}.git origin/master:master
