name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      # PG_PASS: ${{ secrets.PG_PASS }}
      # DATABASE_URL: postgresql://postgres:${{ secrets.SECRET_PASSWORD }}@postgres/postgres
      DJANGO_SETTINGS_MODULE: config.ci_settings
      # SECRET_KEY: ${{ secrets.SECRET_KEY }}
      # PORT: 8000
      CONSUMER_KEY : ${{ secrets.CONSUMER_KEY }}
      CONSUMER_SECRET : ${{ secrets.CONSUMER_SECRET }}
      ACCESS_TOKEN : ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET : ${{ secrets.ACCESS_TOKEN_SECRET }}

    steps:
    - uses: actions/checkout@v1
    - name: Build the docker-compose stack
      run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d
    - name: Check running containers
      run: docker ps -a
    - name: Check logs
      run: docker logs visualizingTweets-django

  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: config.ci_settings

    needs: [build]
    steps:
    - name: Run test suite
      run: docker exec visualizingTweets-django python manage.py test

  deploy:
    # env:
    #   HEROKU_API_KEY: 

    needs: [test]
    steps:
    - uses: actions/checkout@v1
    - name: Push to Heroku
      run: git push -f https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP }}.git origin/master:master
